##KNN

supervised ML -->Classification
woeks best on similarities
store complete data as training data----takes new data to check similarities
non parametric-----lazy learner


lazylearner 
no training phase
memorize the dataset
new data ==> calculate the labels


eg
CAT / DOG ---KNN ----SIMILARITY MEASURE

new data => CAT         ----|
||          DOG         ----|==>MOST SIMILAR=====>PUT INTO CATEGORY  
||
\/
FEATURES



BASICALLY SEES THAT NEW DATAPOINT IS CLOSER TO WHICH LABEL OF THE EXISTING DATASET
USING EUCLIDEAN DISTANCE


STEPS

1)K=> NO. OF NEIGHBOURS (at least 5)

2)euclidean distance/manhattan dist etc

3)minimum distance

s belongs to == 3-A,,or,,2--B
so A it is

K = no. of nearest neighbours

HOW TO SELECT K



NO PARTICULAR VALUE

GENERALLY K SHOULDNt  be low like 1,2 or large

so we usually take k=5

In [2]:
import pandas as pd
import numpy as np
import sklearn

In [4]:
from sklearn.datasets import load_iris
iris = load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [5]:
df =pd.DataFrame(iris["data"])
df.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [6]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [8]:
X = df
Y = iris.target

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.25,random_state=69)

In [16]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

In [19]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [20]:
y_pred = knn.predict(x_test)
y_pred

array([0, 1, 0, 2, 0, 0, 1, 2, 2, 0, 1, 2, 0, 1, 2, 1, 1, 2, 1, 2, 2, 1,
       0, 0, 2, 0, 2, 2, 1, 0, 0, 0, 0, 2, 2, 2, 0, 1])

In [21]:
x_new=np.array([[5,2.9,4.2,8.4]])
knn.predict(x_new)

array([2])

In [23]:
iris['target_names'][knn.predict(x_test)]

array(['setosa', 'versicolor', 'setosa', 'virginica', 'setosa', 'setosa',
       'versicolor', 'virginica', 'virginica', 'setosa', 'versicolor',
       'virginica', 'setosa', 'versicolor', 'virginica', 'versicolor',
       'versicolor', 'virginica', 'versicolor', 'virginica', 'virginica',
       'versicolor', 'setosa', 'setosa', 'virginica', 'setosa',
       'virginica', 'virginica', 'versicolor', 'setosa', 'setosa',
       'setosa', 'setosa', 'virginica', 'virginica', 'virginica',
       'setosa', 'versicolor'], dtype='<U10')

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
y_pred = knn.predict(x_test)
cm= confusion_matrix(y_test,y_pred)
print(cm)

[[14  0  0]
 [ 0  9  0]
 [ 0  1 14]]


In [25]:
print(accuracy_score(y_test,y_pred))

0.9736842105263158


In [29]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.90      1.00      0.95         9
           2       1.00      0.93      0.97        15

    accuracy                           0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38



# K FOLD Cross Validation

k-fold  validation
#different concept from above

performing dataset

-logistic --SVM,randomForest


take one part of data as test data  

now change the test data to another part

keep it till whole data set have taken part as test data

so it happened 'n' no. of times or 'n folds'

we take their av




In [30]:
x=iris.data
y=iris.target

In [40]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold            #above function/model but more customizable
from sklearn.linear_model import LogisticRegression 
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

# Logistic Regression 

In [34]:
lr_score = cross_val_score(LogisticRegression(),x,y)
lr_score

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [41]:
np.average(lr_score)


0.9733333333333334

In [42]:
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

# Decision Tree Classifier

In [36]:
dt_score = cross_val_score(DecisionTreeClassifier(),x,y)
dt_score

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [37]:
np.average(dt_score)

0.9666666666666668

# Support Vector Machine

In [38]:
svm_score = cross_val_score(SVC(),x,y)
svm_score

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [39]:
np.average(svm_score)

0.9666666666666666

# Web Scraping

#1  find url

#2  inspecting page

#3 find data we want to extract

#4 code

#5 execute

#6 store data

selenium

Beautifulsoup

pandas

scrapy => this one is a framework not a library like above 3